### ISSUE TITLE
Processing the corpus

### ISSUE THREAD

**Issue by SravyaMadupu** [antcont/GeLeCo#1]
Could you please mention the steps to be followed to process the whole data in the Corpus? 

Like any dependencies to be installed. Which files are to be run after which ones.

Thanks in advance.

Best Regards,
Sravya

**Comment by antcont** [comment]
Hi Sravya,

the only external libraries used are BeautifulSoup, Selenium,
sentence-splitter (https://github.com/mediacloud/sentence-splitter), SpaCy
(or TreeTagger, according to which one you want to use for POS tagging and
lemmatization; for the TreeTagger, you need to install it in your machine
and the use the treetaggerwrapper), yaspin (for progress visualization
only).

This is the order:
- first, you scrape the URLs for the desired corpus (URLscraper)
- once you have a list of URLs, you scrape the texts (TextMetadataScraper).
Note that the whole corpus is created as a single file at this stage (you
may want to change that)
- Once you have scraped each subcorpus, you run the scripts from
corpus_processing, in the order you see in the README.

Also note that the corpus is built in vertical, pseudo-XML format and can
be used on SketchEngine and NoSketchEngine.

If you need more suggestions, let me know.

Kind regards,

Antonio

Il giorno gio 11 mar 2021 alle ore 09:54 SravyaMadupu <
***@***.***> ha scritto:

**Comment by SravyaMadupu** [comment]
Hello Antonio,

Thanks for the quick reply. I was able to kick start the process. However, I ran into an issue after the process in 1336 files of gesetze website.

The error is something like this:

▰▰▰▰▰▱▱    1337 out of 6594 (20.28%)/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "TextMetadataScraper_G.py", line 59, in <module>
    title = soup.find(class_="jnlangue").get_text(strip=True)
AttributeError: 'NoneType' object has no attribute 'get_text'

**Comment by antcont** [comment]
Hi Sravya,

a broken URL has probably been scraped. 
I added an exception, it should work now.

Let me know if other errors are issued.


Antonio

**Comment by SravyaMadupu** [comment]
Hi Antcont,

Thank you for the reply. That issue is solved. While running URLscapper_R.py I ran into this error.

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\anton\\Downloads\\geckodriver-v0.28.0-win64\\geckodriver.exe': 'C:\\Users\\anton\\Downloads\\geckodriver-v0.28.0-win64\\geckodriver.exe'

Could you please take a look?

Thanks & Regards,
Sravya

**Comment by antcont** [comment]
Hi Sravya,

Selenium needs a webdriver of the browser you choose to use (Firefoxe, Chrome, ...). You should specify the location of your webdriver file in line 16.

Kind regards,

Antonio

**Comment by SravyaMadupu** [comment]
Hi Antcont,

I am running it on google colab. Any idea what I could specify in this case?

Thanks & Regards,
Sravya

**Comment by antcont** [comment]
I'm not too familiar with google colab. 
Try the following: https://stackoverflow.com/questions/51046454/how-can-we-use-selenium-webdriver-in-colab-research-google-com

**Comment by SravyaMadupu** [comment]
Now that worked but I ran into a new issue.

Traceback (most recent call last):
  File "/content/drive/MyDrive/bert/GeLeCo/URLscraper/URLscraper_R.py", line 41, in <module>
    click_next()
  File "/content/drive/MyDrive/bert/GeLeCo/URLscraper/URLscraper_R.py", line 34, in click_next
    driver.find_element_by_xpath('//*[@title="weiter"]').click()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@title="weiter"]"}
  (Session info: headless chrome=89.0.4389.82)

**Comment by SravyaMadupu** [comment]
I am able to get the Corpus now. Thank you so much for all the patience and help. Closing the issue now.
